version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./server/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  firebase:
    build: ./docker/firebase
    restart: always
    volumes:
      - ./docker/firebase:/opt/workspace:cached
    ports:
      - 9099:9099 # Auth
      - 4000:4000 # Emulator Suite UI
    env_file:
      - ./server/.env
    working_dir: /opt/workspace
    command: firebase emulators:start --import=seeder

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000 # Storage
      - 9001:9001 # Console
    env_file:
      - ./server/.env
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/policies:/policies
    entrypoint: []
    command: >
      sh -c "cp -r /policies/* /data/.minio.sys/;
      minio server /data --console-address :9001;"

volumes:
  mysql_data:
    driver: local
